version: '3'

services:
  library-app:
    image: thetombrider/library-app:latest
    container_name: library-app
    ports:
      - "8501:8501"
    volumes:
      - library-db:/data
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
      - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"

volumes:
  library-db:
    name: library-db-data